//EJERCICIO 3 
//Completar las condiciones de los if del siguiente script para que los mensajes se muestren siempre de forma correcta: 


var num1 = 5; 
var num2 = 8; 
if(num1 < num2) { 
console.log("numero1 no es mayor que numero2"); 
} 
if(num2) { 
console.log("numero2 es positivo"); 
} 
if(num1) { 
console.log("numero1 es negativo o distinto de cero"); 
} 
if(num1 < num2) { 
console.log("Incrementar en 1 unidad el valor de numero1 no lo hace mayor o igual que numero2"); 
} 
